---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: oracle8
    image: oraclelinux:8
    pre_built_image: true
  - name: ubuntu
    image: ubuntu:latest
    pre_built_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
