---
- name: Install Vector | YUM install
  become: true
  ansible.builtin.yum:
    name: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm
    state: present
    sslverify: false
    validate_certs: false
  notify: restart vector service
